# Generated by Django 3.0.7 on 2020-07-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('anime_type', models.CharField(blank=True, max_length=50, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('anime_rating', models.FloatField(blank=True, null=True)),
                ('members', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('evaluation', models.FloatField()),
                ('anime_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommend.Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('evaluation', models.FloatField()),
                ('anime_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommend.Anime')),
            ],
        ),
    ]
