# Generated by Django 3.0.7 on 2020-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
