# Generated by Django 3.0.7 on 2020-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_remove_result_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_rating',
            field=models.FloatField(blank=True, max_length=10.0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='evaluation',
            field=models.FloatField(max_length=10.0),
        ),
        migrations.AlterField(
            model_name='result',
            name='evaluation',
            field=models.FloatField(max_length=10.0),
        ),
    ]
