# Generated by Django 3.0.7 on 2020-07-26 11:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_auto_20200709_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultKNN',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('evaluation', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('anime_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommend.Anime')),
            ],
        ),
    ]
